### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Sognineibicchieri** [ivanliu1989/Driver-Telematics-Analysis#1]
Dear Ivan,

Thanks a lot for sharing your code and experience in this contest. I am at the moment studying the driving behaviour area and unfortunately axa has deleted the data for this contest. Do you happen to have the full dataset that you can share?

Many thanks again and look forward to your kind feedback,
lily

**Comment by ivanliu1989** [comment]
Hi @lzh626, unfortunately I didn't keep the data from my end but you might be able to find them under competition page from kaggle. If they are deleted from kaggle, it's probably because the data are not shareable to the public. 
Sorry I am not able to help your request.
